remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [3-D Structures of Organic Compounds]
description: [This website shows our Hackathon project which takes organic compounds and displays them in three dimensional form.]

